### ISSUE TITLE
Is this the official code for BIC ?

### ISSUE THREAD

**Issue by danghieuan** [LzyFischer/BIC#2]
Hello @LzyFischer,
I'm interested in text-graph interaction for the idea of detecting Twitter bots. 

I wanted to ask if this is the official code for the BIC paper ?

Thanks.

**Comment by LzyFischer** [comment]
yes，this is the official code.





------------------ Original ------------------
From: An Dang-Hieu ***@***.***&gt;
Date: Wed,Jun 28,2023 0:32 PM
To: LzyFischer/BIC ***@***.***&gt;
Cc: LzyFischer ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [LzyFischer/BIC] Official code of BIC ? (Issue #2)





 
Hello @LzyFischer,
 I'm interested in text-graph interaction for the idea of detecting Twitter bots.
 
I wanted to ask if this is the official code for the BIC paper ?
 
Thanks.
